### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by anykey111** [bazurbat/jagen#4]
Hi, i saw you have landed initial Rust support.
Currently I'm using CMake and run Cargo as ExternalProject because it fit well with existing C projects, simplify lot of things like strip, deploy and passing target options.

Would be nice to see how build.type='rust' intended to use.

sample of project using Rust+CMake:

### Findcargo.cmake

```
set(CARGO "$ENV{HOME}/.cargo/bin/cargo")
set(CARGO_CROSS PKG_CONFIG_ALLOW_CROSS=1 PKG_CONFIG_PATH=$ENV{jagen_target_dir}/usr/lib/pkgconfig ${CARGO})
```

### CMakeLists.txt

```
project(astindex2)

find_package(cargo)

include(ExternalProject)

set_directory_properties(PROPERTIES EP_PREFIX ${CMAKE_BINARY_DIR}/rust)

set(CRATE_DIR "$ENV{jagen_src_dir}/${PROJECT_NAME}")

add_custom_target(${PROJECT_NAME} ALL
  COMMAND ${CARGO_CROSS} rustc -v --release --target arm-unknown-linux-gnueabi -- -L $ENV{jagen_target_dir}/usr/lib
  WORKING_DIRECTORY ${CRATE_DIR})

install(FILES ${CRATE_DIR}/target/arm-unknown-linux-gnueabi/release/lib${PROJECT_NAME}.so DESTINATION lib)
install(FILES ${CRATE_DIR}/include/astcatalog.h DESTINATION include)
```

### jagen/lib/pkg/rust-arm-toolchain.lua

```
return {
    source = {
        type = 'dist',
        location = 'http://10.0.2.2/sw/linux/dist/rust-1.24.1.tar.bz2',
    },
    build = {
        in_source = true,
        toolchain = false
    }
}
```

### jagen/lib/pkg/rust-arm-toolchain.sh

```
#!/bin/sh

CARGO_HOME="$HOME/.cargo"
RUSTUP_HOME="$HOME/.rustup"

jagen_pkg_unpack() {
    toolchain_unpack "$pkg_name" "$pkg_source_dir"
    pkg_run rm -rf "$CARGO_HOME"
    pkg_run rm -rf "$RUSTUP_HOME"
    pkg_run ln -sf "$pkg_source_dir/.cargo" "$CARGO_HOME"
    pkg_run ln -sf "$pkg_source_dir/.rustup" "$RUSTUP_HOME"
}

#todo: consider using rustup
RUSTUP_INIT="${jagen_dist_dir}/rustup-init"
RUSTUP_INIT_URL="https://static.rust-lang.org/rustup/archive/1.11.0/x86_64-unknown-linux-gnu/rustup-init"

jagen_pkg_unpack_todo() {
    if [ ! -e "$RUSTUP_INIT" ]; then
        pkg_run wget -r -N -c -O "$RUSTUP_INIT" "$RUSTUP_INIT_URL"
    fi

    [ -L "$CARGO_HOME" ] && pkg_run rm "$CARGO_HOME"
    [ -L "$RUSTUP_HOME" ] && pkg_run rm "$RUSTUP_HOME"

    pkg_run chmod +x "$RUSTUP_INIT"
    pkg_run "$RUSTUP_INIT" -y -v --default-toolchain 1.24.1
    pkg_run rustup target add arm-unknown-linux-gnueabi
}
```

**Comment by bazurbat** [comment]
The "rust" build type is for pure cargo projects for now. Given the Jagen revision b9b9f8 the simplest instruction to use it is:
```shell
mkdir root-rust && cd root-rust
curl -fsSL https://raw.githubusercontent.com/bazurbat/jagen/master/init | sh
cargo new --bin src/hello
echo "package { 'hello', 'host', build = 'rust' }" > rules.lua
./jagen build
```
This will initialize a new project root, create "hello" package, download the latest stable rust toolchain using rustup and build the "hello" project. The resulting executable will be put in `build/hello/host/release` directory. The downloaded rust toolchains will be found in the `dist/rustup` directory.

Perhaps more interesting case is automatic cross-compilation setup which just landed in aforementioned commit. Add the following to the `rules.lua`.
```lua
package { 'hello', 'target',
    build = { 'rust',
        system = 'arm-unknown-linux-gnueabi',
        toolchain = 'linaro-arm-4.9'
    }
}
```
Add the following to the "hello" project cargo config (`src/hello/.cargo/config`):
```ini
[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"
```
Run `./jagen build` again. It should download the linaro-4.9 toolchain, add the arm target to the current rust toolchain, build the hello project again and link it using the specified toolchain. The resulting binary can be found in `build/hello/target/arm-unknown-linux-gnueabi/release` directory. See more details about cargo config in the [Taking Rust everywhere with rustup](https://blog.rust-lang.org/2016/05/13/rustup.html) post.

It this time the rust support is experimental and subject to change. I'm not sure if it covers your use case but this is all I've implemented so far.

**Comment by bazurbat** [comment]
I've implemented automatic generation of cargo config, so the step of adding it to the project's directory from the last comment is no longer necessary. The generator also takes into account an actual toolchain's build system and issues a warning if it was not found. Musl and Android variants also work, Jagen takes care of all intermediate steps such as adding targets to cargo and extracting standalone toolchains. Here are some example rules to experiment:
```lua
package { 'hello', 'host',
    build = 'rust'
}
```
Use default host toolchain.
```lua
package { 'hello', 'host',
    build = { 'rust',
        system = 'x86_64-unknown-linux-musl',
    }
}
```
Use default host toolchain but link with musl instead of libc, this will produce fully static executable.
```lua
package { 'hello', 'target',
    build = { 'rust',
        system = 'arm-unknown-linux-gnueabi',
        toolchain = 'linaro-arm-4.9',
    }
}
```
Use linaro arm 4.9 toolchain to and arm-unknown-linux-gnueabi target.
```lua
package { 'hello', 'target',
    build = { 'rust',
        system = 'arm-unknown-linux-musleabi',
        toolchain = 'linaro-arm-4.9',
    }
}
```
The same toolchain but with musl libc, produces fully static executable.
```lua
package { 'hello', 'target',
    build = { 'rust',
        system = 'arm-linux-androideabi',
        toolchain = 'android-standalone-arm-r16b',
    }
}
```
Use Android ARM toolchain, also produces fully static executables.

There are other toolchains available which can be used instead of `linaro-arm-4.9` above:

- linaro-aarch64-5.3.lua
- linaro-arm-4.8.lua
- linaro-arm-5.4.lua
- linaro-arm-6.4.lua
- linaro-arm-7.2.lua

MIPS variant should also work, but not with musl (probably the toolchain is too old):
```lua
package { 'hello', 'target',
    build = { 'rust',
        system = 'mips-unknown-linux-gnu',
        toolchain = 'sourcery-mips-2012.03',
    }
}
```

**Comment by bazurbat** [comment]
There is another feature which is now possible: using rust build for packages residing inside the subdirectory of another package.
```lua
package { 'astindex2', 'host',
    source = {
        dir = '$karaoke_player_source_dir/astindex2',
    },
    build = 'rust',
    use = 'karaoke-player'
}
```
This rule assumes that the `astindex2` is in a subdirectory of `karaoke-player` package. The `use` rule is necessary to make the `$karaoke_player_source_dir` definition available which will be expanded during the build. It also establishes the dependency so that the `karaoke-player` will be checked out and its environment exported before the build of `astindex2` starts

**Comment by bazurbat** [comment]
Actually this was completed some time ago. There is even a [documentation section for Rust](/bazurbat/jagen/blob/master/doc/Rust.md) now. Jagen version 5.3 or later is required. I do not use this myself much unfortunately but intend to maintain the support. Comments, proposals, issue reports are appreciated!
